#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2026 IBM Corporation. All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../..)

APP = kv_host

SPDK_LIB_LIST = nvme

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
