#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2026 IBM Corporation. All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../..)

TEST_FILE = kv_host_shim_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
